### ISSUE TITLE
Problems with disable draggable circle

### ISSUE THREAD

**Issue by NortonPSouza** [GIovaneSantosSilva/garea.js#1]
When a use "this.manager.create", the points stayed draggable, but is not necessary. And I request a functionality for this case.

**Comment by giovanesantossilva** [comment]
Solved in the new version available on npm https://www.npmjs.com/package/garea.js/v/1.0.3 available in the doc.

Example
```js
const area = crop.getDraw('area');
area.setDisable(true);
```
